name: Auto Assign Reviewers
on:
  pull_request:
    types: [opened, edited]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/auto-assign@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          addReviewers: true
          reviewers: |
            - OlyaPolya
            - Konstantsin-Shumak
            - AnhelinaVr
          numberOfReviewers: 0
