name: Auto Assign Reviewers
on:
  pull_request:
    types: [opened, edited]
permissions: write-all
jobs:
  run:
  permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/auto-assign@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          addAssignees: false
          addReviewers: true
          reviewers: |
            OlyaPolya
            Konstantsin-Shumak
            AnhelinaVr
          numberOfReviewers: 0
